FROM nginx:latest
ARG BUNDLE_ENTERPRISE__CONTRIBSYS__COM

ENV BUNDLE_ENTERPRISE__CONTRIBSYS__COM=${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}
RUN echo $BUNDLE_ENTERPRISE__CONTRIBSYS__COM
RUN env
RUN ls /tmp
