name: "Test Init + Build"

on:
  workflow_dispatch:

jobs:
  call-init:
    uses: ./.github/workflows/init.yaml
    with:
      docker_image_name: my-test-image
      customer_name: testcustomer
    outputs:
      environment: ${{ steps.init_job.outputs.environment }}
      sha_short: ${{ steps.init_job.outputs.sha_short }}
      run_deployment: ${{ steps.init_job.outputs.run_deployment }}
      docker_image_name: ${{ steps.init_job.outputs.docker_image_name }}

  build:
    needs: [call-init]
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs from init
        run: |
          echo "Environment: ${{ needs.call-init.outputs.environment }}"
          echo "SHA short: ${{ needs.call-init.outputs.sha_short }}"
          echo "Run deployment: ${{ needs.call-init.outputs.run_deployment }}"
          echo "Docker image name: ${{ needs.call-init.outputs.docker_image_name }}"
