name: Init Workflow

on:
  workflow_call:
    inputs:
      customer_name:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setVars.outputs.environment }}
      sha_short: ${{ steps.setVars.outputs.sha_short }}
      run_deployment: ${{ steps.setVars.outputs.run_deployment }}
      docker_image_name: ${{ inputs.docker_image_name }}
    steps:
      - name: Set variables
        id: setVars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            env_name="prod"
          else
            env_name="dev01"
          fi
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            deploy="false"
          else
            deploy="true"
          fi
          sha_short=$(git rev-parse --short "$GITHUB_SHA")

          echo "environment=$env_name" >> "$GITHUB_OUTPUT"
          echo "sha_short=$sha_short" >> "$GITHUB_OUTPUT"
          echo "run_deployment=$deploy" >> "$GITHUB_OUTPUT"

      - name: Debug print
        run: |
          echo "Environment: ${{ steps.setVars.outputs.environment }}"
          echo "SHA short: ${{ steps.setVars.outputs.sha_short }}"
          echo "Run deployment: ${{ steps.setVars.outputs.run_deployment }}"
          echo "Docker image name: ${{ inputs.docker_image_name }}"
