name: Test pnpm Cache

on:
  workflow_dispatch:
env:
  DUPLO_HOST: https://qa-aws.duplocloud.net/
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  SERVICE_NAME: web
  DUPLO_TENANT: demo

jobs:
  pnpm_cache_test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Enable Docker BuildKit for cache
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Retrieve Duplo Token
        run: echo "DUPLO_TOKEN=${{ secrets.DUPLO_TOKEN }}" >> $GITHUB_ENV

      - name: Duplo Setup
        uses: duplocloud/actions/setup@v0.0.10

      - name: Restore pnpm store cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('dummy-frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Build and Push Docker Image
        uses: duplocloud/actions/build-image@v0.0.10
        id: build-and-push-backend
        with:
          repo: ${{ env.SERVICE_NAME }}
          platforms: linux/amd64
          cache: false
          context: dummy-frontend
