name: Test pnpm Cache

on:
  workflow_dispatch:

jobs:
  pnpm_cache_test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore pnpm store cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('dummy-frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Build Docker image with mounted cache
        run: |
          docker build \
            --build-arg NODE_ENV=development \
            --build-context store=type=local,src=$HOME/.pnpm-store \
            --progress=plain \
            --file dummy-frontend/Dockerfile \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg STORE_PATH=/root/.pnpm-store \
            --build-arg PNPM_HOME=/root/.pnpm-store \
            --output type=docker \
            dummy-frontend
        env:
          DOCKER_BUILDKIT: 1
