name: Test pnpm Cache

on:
  push:
    paths:
      - 'dummy-frontend/**'
      - '.github/workflows/pnpm-cache-test.yml'

jobs:
  pnpm_cache_test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: dummy-frontend/pnpm-lock.yaml

      - name: Restore pnpm store cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('dummy-frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps with pnpm
        working-directory: dummy-frontend
        run: pnpm install
