name: Test Python
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag or SHA to deploy (e.g. v1.2.3 or sha256:abc...)'
        required: true

# env:
  # DUPLO_HOST: https://duplo.internal.root.credit/
  # DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  # SERVICE_NAME: backend-api
  # REPO : backend
  # DUPLO_TENANT: dev01

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   env:
  #     ECR_REGISTRY: 277707140645.dkr.ecr.us-west-2.amazonaws.com
      
  #   environment: development
  #   steps:
  #     - name: Retrieve Duplo Token
  #       run: |
  #         echo "DUPLO_TOKEN=${{ secrets.DUPLO_TOKEN }}" >> $GITHUB_ENV

  #     - name: Duplo Setup
  #       uses: duplocloud/actions/setup@v0.0.5

  #     - name: Update backend Service
  #       uses: duplocloud/actions/update-image@v0.0.5
  #       with:
  #         name: ${{ env.SERVICE_NAME }}
  #         image: ${{ env.ECR_REGISTRY }}/${{env.REPO}}:${{ github.event.inputs.image_tag }}
  #         type: service
