name: Manual Test Run for Reusable Workflow

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      python_version: '3.11'
      poetry_version: '1.8.2'
      checkout_ref: ${{ github.ref_name }}
