name: Run Tests on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      python_version: '3.11'
      poetry_version: '1.8.2'
      checkout_ref: ${{ github.ref_name }}
